name: pumpkin lemma
description: "Jekyll Bulma Theme, Bulma.io CSS Framework Jekyll Template for Developers"
baseurl: ""
url: "https://pumpkinlemma.github.io/"
download: "#"
social:
  github: pumpkinlemma
  email: lemmapumpkin@gmail.com
  facebook: /
  twitter: /
  instagram:
  tumblr:
author:
  name: 
  bio: 
  email: 
  image: 
  github: 
  facebook: 
  twitter: 
  instagram:
  tumblr:
  show_on_post: false
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - jekyll-timeago

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor

jekyll_timeago:
  depth: 1 # Level of detail
  today: 'today'
  yesterday: 'yesterday'
  tomorrow: 'tomorrow'
  and: 'and'
  suffix: 'ago'
  prefix: ''
  suffix_future: ''
  prefix_future: 'in'
  years: 'years'
  year: 'year'
  months: 'months'
  month: 'month'
  weeks: 'weeks'
  week: 'week'
  days: 'days'
  day: 'day'
